---
- name: Copy MOTD.sh
  template:
    src: 'login-info.sh.j2'
    dest: /etc/login-info.sh
    mode : '0777'
  become: true

- name: Add the path of login-info.sh at the end of the system profile
  lineinfile:
    path: /etc/profile
    line: "/etc/login-info.sh"
  become: true
