---

- name: Disable Ubuntu motd-news
  lineinfile:
    path: '/etc/default/motd-news'
    regexp: '^ENABLED='
    line: 'ENABLED=0'
  become: true
  ignore_errors: true

- name: Get all files on update-motd.d
  shell: 'ls /etc/update-motd.d'
  register: ubuntu_update_motd

- name: Set the fact
  set_fact:
    ubuntu_update_motd={{ ubuntu_update_motd.stdout_lines }}

- name: Change file ownership, group and permissions
  file:
    path: '/etc/update-motd.d/{{ ubuntu_update_motd_files_loop }}'
    mode: '0644'
  with_items: '{{ ubuntu_update_motd }}'
  loop_control:
    loop_var: ubuntu_update_motd_files_loop
  become: true

- name: Copy custom MOTD
  template:
    src: 'login-info.sh.j2'
    dest: '/etc/update-motd.d/00-login-info'
    owner: root
    group: root
    mode: '0755'
  become: true
