---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: molecule-vagrant-centos7-bento-ansible-role-server_banners_prompts
    box: bento/centos-7
    memory: 512
    cpus: 1
  - name: molecule-vagrant-ubuntu-18.04-bento-ansible-role-server_banners_prompts
    box: bento/ubuntu-18.04
    memory: 512
    cpus: 1
  - name: molecule-vagrant-archlinux-ansible-role-server_banners_prompts
    box: archlinux/archlinux
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  # options:
  #   become: true
verifier:
  name: ansible
